const data = [
    {
        id: 1,
        name: 'Beverly Springfield',
        location: 'London',
        type: 'Bungalow',
        price: 2100,
        beds: '3',
        baths: '2',
        address: '123 Main St',
        sqft: '1000',
        image: 'https://cdn.houseplansservices.com/content/hc9vdnsvn5a1b22niq0o22ellq/w575.jpg'
    },
    {
        id: 2,
        name: 'Faulkner Ave',
        location: 'New York',
        type: 'Apartment',
        price: 4500,
        beds: '4',
        baths: '4',
        address: 'Green St 12 apt. 3',
        sqft: '2000',
        image: 'https://media-cdn.tripadvisor.com/media/vr-splice-j/00/17/88/ba.jpg'
    },
    {
        id: 3,
        name: 'Palm Harbor',
        location: 'Seattle',
        type: 'Apartment',
        price: 1500,
        beds: '2',
        baths: '1',
        address: 'Blue St 12 apt. 13',
        sqft: '500',
        image: 'https://www.decorilla.com/online-decorating/wp-content/uploads/2020/08/Modern-Apartment-Decor-.jpg'
    },
    {
        id: 4,
        name: 'The Willows',
        location: 'Atlanta',
        type: 'Loft',
        price: 6400,
        beds: '5',
        baths: '4',
        address: 'Red St 12 apt. 4',
        sqft: '3000',
        image: 'https://images.adsttc.com/media/images/5f50/15a4/b357/65c8/8600/0070/newsletter/01.jpg?1599083931'
    },
    {
        id: 5,
        name: 'The Orchard House',
        location: 'Los Angeles',
        type: 'Mansion',
        price: 9400,
        beds: '7',
        baths: '6',
        address: 'Yellow St 12 apt. 5',
        sqft: '8000',
        image: 'https://ca-times.brightspotcdn.com/dims4/default/8cc49f1/2147483647/strip/true/crop/4938x2936+0+0/resize/1486x884!/quality/90/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F90%2F03%2F12089105491898b4bf70102eb77d%2Ffi-hotprop-makowsky-billionaire.jpg'
    },
    {
        id: 6,
        name: 'Oak Barn',
        location: 'New York',
        type: 'Bungalow',
        price: 5400,
        beds: '4',
        baths: '3',
        address: 'Park St 12 apt. 61',
        sqft: '1400',
        image: 'https://ulrichome.com/wp-content/uploads/2018/03/SHD-2015022-DESIGN4_Color2_View03.jpg'
    },
    {
        id: 7,
        name: 'Adobe Star',
        location: 'Seattle',
        type: 'Condo',
        price: 3400,
        beds: '3',
        baths: '2',
        address: '89th St 12 apt. 7',
        sqft: '2500',
        image: 'https://img.jamesedition.com/listing_images/2021/08/24/13/46/28/a05f74c8-0610-4dfe-9f8b-85bbd7137740/je/620x465xc.jpg'
    },
    {
        id: 8,
        name: 'Meadow View',
        location: 'Seattle',
        type: 'Mansion',
        price: 7800,
        beds: '6',
        baths: '5',
        address: 'New St 12 apt. 8',
        sqft: '6750',
        image: 'https://cdn.homedit.com/wp-content/uploads/2021/11/Modern-Mansion.jpg'
    },
    {
        id: 9,
        name: 'Hedgerows',
        location: 'Los Angeles',
        type: 'Apartment',
        price: 4900,
        beds: '3',
        baths: '3',
        address: '529 Main St',
        sqft: '1800',
        image: 'https://techcrunch.com/wp-content/uploads/2019/03/blueground-apartment-2-2-2.jpg'
    },
    {
        id: 10,
        name: 'The Willows',
        location: 'Los Angeles',
        type: 'Loft',
        price: 2900,
        beds: '2',
        baths: '3',
        address: '1529 Lake St apt. 10',
        sqft: '1400',
        image: 'https://cdn.decoist.com/wp-content/uploads/2021/01/Gorgeous-and-space-savvy-modern-industrial-loft-in-Indonesia-with-a-lovely-backyard-54080.jpg'
    },
    {
        id: 11,
        name: 'Huntington',
        location: 'Seattle',
        type: 'Bungalow',
        price: 3180,
        beds: '3',
        baths: '4',
        address: 'Old St 12 apt. 11',
        sqft: '2200',
        image: 'https://designingidea.com/wp-content/uploads/2020/11/bungalow-house-design-with-front-porch-ss.jpg'
    },
    {
        id: 12,
        name: 'Colmar Hills',
        location: 'New York',
        type: 'Mansion',
        price: 12040,
        beds: '10',
        baths: '12',
        address: 'Beverly way 12 apt. 12',
        sqft: '9200',
        image: 'https://loveincorporated.blob.core.windows.net/contentimages/gallery/574bc9b2-d0e0-43e3-aa71-33287a758b15-f932a3fb-4621-4e69-967c-10151ecf7b28-la-mega-mansion-underground-secret.jpg'
    },
    {
        id: 13,
        name: `The Cole's`,
        location: 'London',
        type: 'Condo',
        price: 1090,
        beds: '2',
        baths: '1',
        address: 'West St 12 apt. 13',
        sqft: '750',
        image: 'https://www.brickunderground.com/sites/default/files/styles/blog_primary_image/public/blog/images/190501Tribeca111MurrayStMAINPIC.jpg'
    },
    {
        id: 14,
        name: 'The Usher',
        location: 'Chicago',
        type: 'Mansion',
        price: 7200,
        beds: '6',
        baths: '7',
        address: 'Ash St 12 apt. 14',
        sqft: '3750',
        image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bWFuc2lvbnxlbnwwfHwwfHw%3D&w=1000&q=80'
    },
    {
        id: 15,
        name: 'Ascension',
        location: 'Atlanta',
        type: 'Bungalow',
        price: 4560,
        beds: '4',
        baths: '4',
        address: 'Bolt St 12 apt. 14',
        sqft: '1750',
        image: 'https://thehousedesignhub.com/wp-content/uploads/2021/07/171p-1024x700.jpg'
    },
]

export default data;